### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by apu52**
Hello Sir ,
I have added some cool API data boxes to your repo.
Please go through it
& After reviewing if possible please merge it under APERTRE'24

### CODE REVIEW

**Comment by apu52** [comment]
@sayandippaul Please go through my PR & please merge it under APERTRE'24

**Review by techmannih — APPROVED** [review]

**Comment by apu52** [comment]
@sayandippaul @techmannih Can you  Please merge it under APERTRE & add the related labels to it?

**Comment by techmannih** [comment]
@apu52 
No worries, @sayandippaul  will merge this pr under apertre'24

**Comment by sayandippaul** [comment]
sorry extremely for being late

**Comment by apu52** [comment]
> sorry extremely for being late

No matter. thank you for merging my PR

**Pull request merged**
